spring:
  application:
    name: book-management-api
  datasource:
    url: jdbc:mysql://144.22.206.71:3306/bookmanagementdb
    username: bookmanagement
    password: Bookmanagement123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080